### ISSUE TITLE
Not showing app updated dialog

### ISSUE THREAD

**Issue by pmrajani** [javiersantos/AppUpdater#134] opened 2018-04-25 09:38 UTC
here is log i can show in my IDE.
E/AppUpdater: Cannot retrieve latest version. Is it configured properly?

setup : 
i have added it on MainActivity onCreate method.

  AppUpdater appUpdater = new AppUpdater(this);
        appUpdater.start();

**Comment by javiersantos** [comment] 2018-04-25 19:59
Duplicate of #132

**Closed by javiersantos** 2018-04-25 19:59 UTC
Labels: invalid
