### ISSUE TITLE
Check APK version from Beta Release

### ISSUE THREAD

**Issue by nawinkhatiwada** [javiersantos/AppUpdater#194] opened 2020-09-02 07:15 UTC
Is there any way to check the apk version from the playstore when the app is in beta release?

**Comment by javiersantos** [comment] 2020-12-28 11:02
Duplicate of #117 and explained in the [wiki](https://github.com/javiersantos/AppUpdater/wiki/UpdateFrom.GOOGLE_PLAY).

**Closed as completed by javiersantos** 2020-12-28 11:02 UTC
Labels: duplicate
