### ISSUE TITLE
Wrong getLastestVersion?

### ISSUE THREAD

**Issue by hendyghsta** [javiersantos/AppUpdater#143] opened 2018-08-01 08:23 UTC
Look!

![screenshot_59](https://user-images.githubusercontent.com/16483874/43510127-3954e056-95a7-11e8-904f-ef2892abd934.jpg)

**Comment by javiersantos** [comment] 2019-08-08 14:20
Duplicate of #140

**Closed by javiersantos** 2019-08-08 14:20 UTC
